POST http://localhost:3333/subscriptions
Content-Type: application/json

{
    "name": "leandro123123",
    "email": "Indicado2@gmail.com",
    "referrer": "Leandro123"
}


###

GET http://localhost:3333/invites/leandro123

###
GET http://localhost:3333/subscribers/leandro123/ranking/clicks