POST http://localhost:3333/subscriptions
Content-Type: application/json

{
    "name": "Leandro Silva",
    "email": "Leandros@gmail.com"
}


###

GET http://localhost:3333/invites/leandro123

###
GET http://localhost:3333/invites/leandro123/ranking/clicks